export { default as makeid } from "./randomString";
export { default as Loading } from "./loading";
export { default as compareObjectArrays } from "./compareObjectArrays";
export { default as searchAndBold } from "./searchAndBold";
// export { default as Prompt} from './Prompt'
export { default as deletePartOfString } from "./deletePartOfAString";
export { default as replaceImage } from "./replaceImage";
export { default as checkForImage } from "./checkForImage";
export { default as jsonParser } from "./jsonParser";
