export { default as Home } from "./Home";
export { default as UserDashboard } from "./User-Dashboard";
export { default as IsAuth } from './User-Dashboard/Is-Auth/isAuth'
export { default as ContentUpload } from "./User-Dashboard/Content-Upload/contentUpload";
export { default as ContentEdit } from "./User-Dashboard/Content-Edit/contentEdit";
export { default as ContentDashboard } from "./Content-Dashboard";
export { default as ContentId } from "./Content-Dashboard/Content-Id/content-id";
export { default as SignIn } from "./Signin";
export { default as SignUp } from "./Signup";
export { default as SearchResults } from "./SearchResults";
export { default as ResetPassword } from './ResetPassword'
